services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: |
      pip install -r build-requirements.txt
      pip install -r requirements.txt
    startCommand: python app.py  # or your main start file
